# Generated by Django 4.2.3 on 2023-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_dish_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='day',
            field=models.CharField(choices=[(0, 'Everyday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0, max_length=1),
        ),
    ]
