# Generated by Django 4.2.3 on 2023-07-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
