# Generated by Django 4.2.3 on 2023-07-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='menu',
        ),
        migrations.AddField(
            model_name='dish',
            name='menus',
            field=models.ManyToManyField(related_name='dishes', to='restaurants.menu'),
        ),
    ]
