# Generated by Django 4.2.3 on 2023-07-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_dish_name_alter_menu_day_alter_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='menus',
        ),
        migrations.AddField(
            model_name='dish',
            name='menus',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.menu'),
        ),
    ]
