# Generated by Django 4.2.3 on 2023-07-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_rename_menus_dish_menu_alter_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.menu', unique=True),
        ),
    ]
