# Generated by Django 4.2.3 on 2023-07-12 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0023_alter_vote_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='votes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
