# Generated by Django 4.2.3 on 2023-07-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0024_remove_menu_votes_alter_vote_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
