# Generated by Django 4.2.3 on 2023-07-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_alter_vote_menu_delete_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
